<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>GivenX.Agent</AssemblyName><Version>1.6.2.9</Version><FileVersion>1.6.2.9</FileVersion></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\GivenX.Shared\GivenX.Shared.csproj" /></ItemGroup>
</Project>
